[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
GO_VERSION = "1.24.2"
HUGO_VERSION = "0.148.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "22"
TZ = "America/Phoenix"
